-- Create the table
CREATE TABLE phone_numbers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    office_name TEXT,
    zip_code TEXT,
    title TEXT,
    phone TEXT,
    dept TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE phone_numbers ENABLE ROW LEVEL SECURITY;

-- Create Policy: Allow public read access
CREATE POLICY "Allow public read access"
ON phone_numbers
FOR SELECT
TO public
USING (true);

-- Create Policy: Allow authorized insert/update (if needed, or just service role)
-- For now, we rely on Service Role for import, or you can enable full access temporarily
-- CREATE POLICY "Allow full access for authenticated users" ON phone_numbers FOR ALL USING (auth.role() = 'authenticated');
